### ISSUE TITLE
Recognise current contributions and cut a release of peakdet _before_ its "physiopy stage".

### ISSUE THREAD

**Issue by smoia** [physiopy/peakdet#29]
As this package moved into peakdet, it would be better to track its former development and the moment it changed ownership with a release cut. @rmarkello, which development stage (hence what version) do you think is more appropriate for this version of `peakdet`? `0.1.0` or `1.0.0`?
Before cutting a release, I would also like to adopt the all-contributors specification to recognise @rmarkello @emdupre @xl624 contributions. Can I kindly ask the three of you to propose your contribution types?

**Comment by rmarkello** [comment]
Hi @smoia, I think I can answer on behalf of everyone:

@emdupre: code, infra
@xl624: code
@rmarkello: code, data, doc, ideas, infra, test, tutorial

Re version: I'd absolutely say `0.1.0`! You definitely want to keep this in beta (i.e., `<1.0.0`) for a while 😁
